### ISSUE TITLE
Support authentication when load external definitions, especially loading external auth definitions

### ISSUE THREAD

**Issue by Flex-Xuan** [serverlessworkflow/sdk-net#53]
**What would you like to be added**:
Support authentication when loading external definitions

**Why is this needed**:
Since security is critical, so if I defined the AuthenticationDefinitions in an external places, when loading it, the external resource must do some authentication works (You don't want everyone can access your username/password, right?) currently, I haven't seen related codes to this in method LoadExternalDefinitionCollectionAsync

**Comment by cdavernas** [comment]
This issue is stale since https://github.com/serverlessworkflow/sdk-net/tree/v1.0.0-alpha1, which enables all external resources to be loaded using a specified authentication definition.

As a side note/warning, you should never store credentials in an external definition, that's what secrets are for.
